//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using Microsoft.AspNetCore.Mvc.Rendering;
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace DNDAuth.Models
{
    public partial class User
    {
        [Key]
        public int UserID { get; set; }
        public string FirstName { get; set; }
        public string LastName { get; set; }
        public string EmailID { get; set; }
        public Nullable<System.DateTime> DateOfBirth { get; set; }
        public string Password { get; set; }
        public bool IsEmailVerified { get; set; }
        public System.Guid ActivationCode { get; set; }

        //public List<SecurityQuestions> SecurityQuestionList = new List<SecurityQuestions>();

        public int SecurityQuesID { get; set; }
        [Key, Column(Order = 1), ForeignKey("SecurityQuesID")]
        public virtual SecurityQuestions SecurityQuestions { get; set; }
        public string SecurityAnswer { get; set; }
    }
}
